In [1]:
print("Hello")

Hello

In [7]:
import pandas as pd

ds1 = pd.read_csv("./Dataset/prices_round_1_day_0.csv", sep=';')
ds1

,day,timestamp,product,bid_price_1,bid_volume_1,bid_price_2,bid_volume_2,bid_price_3,bid_volume_3,ask_price_1,ask_volume_1,ask_price_2,ask_volume_2,ask_price_3,ask_volume_3,mid_price,profit_and_loss
0,0,0,ASH_COATED_OSMIUM,NaN,NaN,NaN,NaN,NaN,NaN,10013.0,30.0,NaN,NaN,NaN,NaN,10013.0,0.0
1,0,0,INTARIAN_PEPPER_ROOT,11991.0,19.0,NaN,NaN,NaN,NaN,12006.0,10.0,12009.0,19.0,NaN,NaN,11998.5,0.0
2,0,100,INTARIAN_PEPPER_ROOT,11994.0,9.0,11991.0,23.0,NaN,NaN,12007.0,9.0,12010.0,23.0,NaN,NaN,12000.5,0.0
3,0,100,ASH_COATED_OSMIUM,9995.0,13.0,NaN,NaN,NaN,NaN,10011.0,13.0,10013.0,30.0,NaN,NaN,10003.0,0.0
4,0,200,INTARIAN_PEPPER_ROOT,11991.0,20.0,NaN,NaN,NaN,NaN,12007.0,11.0,12010.0,20.0,NaN,NaN,11999.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,0,999700,INTARIAN_PEPPER_ROOT,12989.0,20.0,NaN,NaN,NaN,NaN,13007.0,10.0,13010.0,20.0,NaN,NaN,12998.0,0.0
19996,0,999800,INTARIAN_PEPPER_ROOT,NaN,NaN,NaN,NaN,NaN,NaN,13007.0,10.0,13010.0,24.0,NaN,NaN,13007.0,0.0
19997,0,999800,ASH_COATED_OSMIUM,NaN,NaN,NaN,NaN,NaN,NaN,10018.0,27.0,NaN,NaN,NaN,NaN,10018.0,0.0
19998,0,999900,ASH_COATED_OSMIUM,9998.0,21.0,NaN,NaN,NaN,NaN,10016.0,12.0,10019.0,21.0,NaN,NaN,10007.0,0.0
19999,0,999900,INTARIAN_PEPPER_ROOT,12990.0,23.0,NaN,NaN,NaN,NaN,13010.0,23.0,NaN,NaN,NaN,NaN,13000.0,0.0

In [8]:
ds1.describe()

,day,timestamp,bid_price_1,bid_volume_1,bid_price_2,bid_volume_2,bid_price_3,bid_volume_3,ask_price_1,ask_volume_1,ask_price_2,ask_volume_2,ask_price_3,ask_volume_3,mid_price,profit_and_loss
count,20000.0,20000.0000,19219.000000,19219.000000,12937.000000,12937.000000,433.000000,433.000000,19231.000000,19231.000000,13029.000000,13029.000000,401.000000,401.000000,20000.000000,20000.0
mean,0.0,499950.0000,11243.526874,12.864977,11239.155136,22.029760,10928.193995,23.346420,11259.546253,12.832978,11255.027477,22.092486,10934.017456,23.209476,11230.764300,0.0
std,0.0,288682.3503,1266.278322,5.030537,1268.086183,4.520187,1220.920579,4.003481,1265.821902,4.964625,1264.317131,4.505545,1227.431561,4.045493,1349.365749,0.0
min,0.0,0.0000,9976.000000,2.000000,9976.000000,2.000000,9976.000000,11.000000,9984.000000,1.000000,9994.000000,2.000000,9998.000000,8.000000,0.000000,0.0
25%,0.0,249975.0000,9994.000000,10.000000,9991.000000,19.000000,9990.000000,21.000000,10010.000000,10.000000,10012.000000,19.000000,10011.000000,21.000000,10002.000000,0.0
50%,0.0,499950.0000,11991.000000,12.000000,10004.000000,22.000000,9995.000000,23.000000,12007.000000,12.000000,10025.000000,22.000000,10015.000000,23.000000,10018.500000,0.0
75%,0.0,749925.0000,12492.000000,14.000000,12495.000000,25.000000,12317.000000,26.000000,12509.000000,14.000000,12506.000000,25.000000,12361.000000,26.000000,12499.000000,0.0
max,0.0,999900.0000,12993.000000,30.000000,12989.000000,30.000000,12979.000000,30.000000,13010.000000,30.000000,13010.000000,30.000000,12995.000000,30.000000,13007.000000,0.0

In [9]:
ds1.isnull().sum()

day                    0
timestamp              0
product                0
bid_price_1          781
bid_volume_1         781
bid_price_2         7063
bid_volume_2        7063
bid_price_3        19567
bid_volume_3       19567
ask_price_1          769
ask_volume_1         769
ask_price_2         6971
ask_volume_2        6971
ask_price_3        19599
ask_volume_3       19599
mid_price              0
profit_and_loss        0
dtype: int64